var product = [{
    "id": 0,
    "Title": "",
    "Battery": "",
    "Battery features": "",
    "Battery warranty": "",
    "charging time": "",
    "Motor": "",
    "Max speed": "",
    "Warrantyonelectronics": "",
    "Maxrange (@30km/h)": "",
    "Maxrange (@45km/h)": "",
    "Maxrange (@full speed)": "",
    "Other key benefits": "",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png"
}, {
    "id": 1,
    "Title": "Rhyno SE03 Lite",
    "Battery": "1.8kwh",
    "Battery features": "LFPwith1500cyclesActiveBalancingWaterproof(IP67)",
    "Battery warranty": "3years",
    "charging time": " 3hours(12A)",
    "Motor": "1500W",
    "Max speed": "55km/h",
    "Warranty on electronics": "1year",
    "Max range(@30km/h)": "100km",
    "Max range(@45km/h)": "90km",
    "Max range(@full speed)": "60km",
    "Other key benefits": "Fire-safeBattery,Rangeprediction,Comfortableride,Stable and safe",
    "image":"img/1.png"
}, {
    "id": 2,
    "Title": "Rhyno SE03",
    "Battery": "2.7Kwh",
    "Battery features": "LFPwith1500 cycles Active Balancing Waterproof(IP67)",
    "Battery warranty": "3Years",
    "charging time": "4hours(12A)",
    "Motor": "1500W",
    "Max speed": "55km/h",
    "Warranty on electronics": "1year",
    "Max range(@30km/h)": "150km",
    "Max range(@45km/h)": "110km",
    "Max range(@full speed)": "90km",
    "Other key benefits": " Fire-safe battery,Range prediction,Comfortable ride ,Stable and safe",
    "image":"img/2.png"
}, {
    "id": 3,
    "Title": "Rhyno SE03 Max",
    "Battery": "2.7Kwh",
    "Battery features": "LFPwith1500 cycles,ActiveBalancing, Waterproof (IP67)",
    "Battery warranty": "3Years",
    "charging time": "4hours(12A)",
    "Motor": "2000W",
    "Max speed": "65km/h",
    "Warranty on electronics": "1year",
    "Max range(@30km/h)": "120km",
    "Max range(@45km/h)": "100km",
    "Max range(@full speed)": "80km",
    "Other key benefits": " Fire-safe battery,Range prediction,Comfortable ride Stable and safe",
    "image":"img/3.png"
}, {
    "id": 4,
    "Title": "Rhyno SE03 ",
    "Battery": "2.7Kwh",
    "Battery features": "LFPwith1500 cycles,ActiveBalancing, Waterproof (IP67)",
    "Battery warranty": "3Years",
    "charging time": "4hours(12A)",
    "Motor": "2000W",
    "Max speed": "65km/h",
    "Warranty on electronics": "1year",
    "Max range(@30km/h)": "120km",
    "Max range(@45km/h)": "100km",
    "Max range(@full speed)": "80km",
    "Other key benefits": " Fire-safe battery,Range prediction,Comfortable ride Stable and safe",
    "image":"img/6.png"
}, {
    "id": 5,
    "Title": "Rhyno SE03 Max",
    "Battery": "2.7Kwh",
    "Battery features": "LFPwith1500 cycles,ActiveBalancing, Waterproof (IP67)",
    "Battery warranty": "3Years",
    "charging time": "4hours(12A)",
    "Motor": "2000W",
    "Max speed": "65km/h",
    "Warranty on electronics": "1year",
    "Max range(@30km/h)": "120km",
    "Max range(@45km/h)": "100km",
    "Max range(@full speed)": "80km",
    "Other key benefits": " Fire-safe battery,Range prediction,Comfortable ride Stable and safe",
    "image":"img/8.png"
}, {
    "id": 6,
    "Title": "Rhyno SE03 Lite",
    "Battery": "2.7Kwh",
    "Battery features": "LFPwith1500 cycles,ActiveBalancing, Waterproof (IP67)",
    "Battery warranty": "3Years",
    "charging time": "4hours(12A)",
    "Motor": "2000W",
    "Max speed": "65km/h",
    "Warranty on electronics": "1year",
    "Max range(@30km/h)": "120km",
    "Max range(@45km/h)": "100km",
    "Max range(@full speed)": "80km",
    "Other key benefits": " Fire-safe battery,Range prediction,Comfortable ride Stable and safe",
    "image":"img/3.png"
}, {
    "id": 7,
    "Title": "Rhyno SE03 Max",
    "Battery": "2.7Kwh",
    "Battery features": "LFPwith1500 cycles,ActiveBalancing, Waterproof (IP67)",
    "Battery warranty": "3Years",
    "charging time": "4hours(12A)",
    "Motor": "2000W",
    "Max speed": "65km/h",
    "Warranty on electronics": "1year",
    "Max range(@30km/h)": "120km",
    "Max range(@45km/h)": "100km",
    "Max range(@full speed)": "80km",
    "Other key benefits": " Fire-safe battery,Range prediction,Comfortable ride Stable and safe",
    "image":"img/4.png"
}, {
    "id": 8,
    "Title": "Rhyno SE03",
    "Battery": "2.7Kwh",
    "Battery features": "LFPwith1500 cycles,ActiveBalancing, Waterproof (IP67)",
    "Battery warranty": "3Years",
    "charging time": "4hours(12A)",
    "Motor": "2000W",
    "Max speed": "65km/h",
    "Warranty on electronics": "1year",
    "Max range(@30km/h)": "120km",
    "Max range(@45km/h)": "100km",
    "Max range(@full speed)": "80km",
    "Other key benefits": " Fire-safe battery,Range prediction,Comfortable ride Stable and safe",
    "image":"img/6.png"
}, {
    "id": 9,
    "Title": "Rhyno SE03 Lite",
    "Battery": "2.7Kwh",
    "Battery features": "LFPwith1500 cycles,ActiveBalancing, Waterproof (IP67)",
    "Battery warranty": "3Years",
    "charging time": "4hours(12A)",
    "Motor": "2000W",
    "Max speed": "65km/h",
    "Warranty on electronics": "1year",
    "Max range(@30km/h)": "120km",
    "Max range(@45km/h)": "100km",
    "Max range(@full speed)": "80km",
    "Other key benefits": " Fire-safe battery,Range prediction,Comfortable ride Stable and safe",
    "image":"img/7.png"
}, {
    "id": 10,
    "Title": "Rhyno SE03 Max",
    "Battery": "2.7Kwh",
    "Battery features": "LFPwith1500 cycles,ActiveBalancing, Waterproof (IP67)",
    "Battery warranty": "3Years",
    "charging time": "4hours(12A)",
    "Motor": "2000W",
    "Max speed": "65km/h",
    "Warranty on electronics": "1year",
    "Max range(@30km/h)": "120km",
    "Max range(@45km/h)": "100km",
    "Max range(@full speed)": "80km",
    "Other key benefits": " Fire-safe battery,Range prediction,Comfortable ride Stable and safe",
    "image":"img/8.png"
}]